paths:
  paths:
  /products:
    get:
      summary: Obtiene todos los productos
      description: Endpoint que retorna todos los productos si esta logueado el usuario
      tags:
        - Products
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ID:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    code:
                      type: string
                    price:
                      type: number
                    status:
                      type: boolean
                    stock:
                      type: number
                    category:
                      type: string
        500:
          description: Error interno del servidor

          

  /products/{id}:
    get:
      summary: Obtiene un producto por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: success
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor

  /products/pid/{pid}:
    get:
      summary: Obtiene un producto por su PID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: PID del producto
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor

  /:
    post:
      summary: Crea un nuevo producto
      tags:
        - Products
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Producto creado exitosamente
        '401':
          description: No autorizado
        '500':
          description: Error interno del servidor

  /products/{pid}:
    put:
      summary: Actualiza un producto por su PID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: PID del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto actualizado exitosamente
        '404':
          description: Producto no encontrado
        '401':
          description: No autorizado
        '500':
          description: Error interno del servidor