paths:
  /products:
    get:
      summary: Obtiene todos los productos
      responses:
        '200':
          description: OK
        '500':
          description: Error interno del servidor

  /products/{id}:
    get:
      summary: Obtiene un producto por su ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor

  /products/pid/{pid}:
    get:
      summary: Obtiene un producto por su PID
      parameters:
        - in: path
          name: pid
          required: true
          description: PID del producto
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor

  /:
    post:
      summary: Crea un nuevo producto
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Producto creado exitosamente
        '401':
          description: No autorizado
        '500':
          description: Error interno del servidor

  /products/{pid}:
    put:
      summary: Actualiza un producto por su PID
      parameters:
        - in: path
          name: pid
          required: true
          description: PID del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto actualizado exitosamente
        '404':
          description: Producto no encontrado
        '401':
          description: No autorizado
        '500':
          description: Error interno del servidor